apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: public.ecr.aws/f8w6t9j2/todo-docker_app:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001